apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: shared-volume
  containers:
    - name: container-1
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo $(hostname) > /data/hostname1.txt; sleep 3600"]
      volumeMounts:
        - name: shared-volume
          mountPath: /data
    - name: container-2
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo $(hostname) > /data/hostname2.txt; sleep 3600"]
      volumeMounts:
        - name: shared-volume
          mountPath: /data
    - name: container-3
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 5; ls /data; cat /data/hostname1.txt /data/hostname2.txt; sleep 3600"]
      volumeMounts:
        - name: shared-volume
          mountPath: /data
