apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: replica-set-1-app
  template:
    metadata:
      labels:
        app: replica-set-1-app
    spec:
      containers:
      - name: busyboxs
        image: busybox
