apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: c3FsMDE=  # Base64 encoded for 'sql01'
  MYSQL_USER: dXNlcjE=      # Base64 encoded for 'user1'
  MYSQL_PASSWORD: cGFzc3dvcmQ= # Base64 encoded for 'password'
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM= # Base64 encoded for 'password123'
